ALTER TABLE t_expenses AUTO_INCREMENT = 1;
ALTER TABLE t_expenses_category AUTO_INCREMENT = 1;
ALTER TABLE t_incomes AUTO_INCREMENT = 1;
ALTER TABLE t_incomes_category AUTO_INCREMENT = 1;
ALTER TABLE t_payment_methods AUTO_INCREMENT = 1;

