//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ef_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHomeEntities : DbContext
    {
        public MyHomeEntities()
            : base("name=MyHomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_expenses> t_expenses { get; set; }
        public virtual DbSet<t_expenses_category> t_expenses_category { get; set; }
        public virtual DbSet<t_incomes> t_incomes { get; set; }
        public virtual DbSet<t_incomes_category> t_incomes_category { get; set; }
        public virtual DbSet<t_payment_methods> t_payment_methods { get; set; }
    }
}
