//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("myhome2013Model", "EXP_CATEGORY_NAME", "t_expenses_category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.t_expenses_category), "t_expenses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.t_expenses), true)]
[assembly: EdmRelationshipAttribute("myhome2013Model", "EXP_PAYMENT_METHOD", "t_payment_methods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.t_payment_methods), "t_expenses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.t_expenses), true)]
[assembly: EdmRelationshipAttribute("myhome2013Model", "INC_CATEGORY_NAME", "t_incomes_category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.t_incomes_category), "t_incomes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.t_incomes), true)]
[assembly: EdmRelationshipAttribute("myhome2013Model", "INC_PAYMENT_METHOD", "t_payment_methods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.t_payment_methods), "t_incomes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.t_incomes), true)]

#endregion

namespace Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class myhome2013Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new myhome2013Entities object using the connection string found in the 'myhome2013Entities' section of the application configuration file.
        /// </summary>
        public myhome2013Entities() : base("name=myhome2013Entities", "myhome2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myhome2013Entities object.
        /// </summary>
        public myhome2013Entities(string connectionString) : base(connectionString, "myhome2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myhome2013Entities object.
        /// </summary>
        public myhome2013Entities(EntityConnection connection) : base(connection, "myhome2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<categoryview> categoryviews
        {
            get
            {
                if ((_categoryviews == null))
                {
                    _categoryviews = base.CreateObjectSet<categoryview>("categoryviews");
                }
                return _categoryviews;
            }
        }
        private ObjectSet<categoryview> _categoryviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_expenses> t_expenses
        {
            get
            {
                if ((_t_expenses == null))
                {
                    _t_expenses = base.CreateObjectSet<t_expenses>("t_expenses");
                }
                return _t_expenses;
            }
        }
        private ObjectSet<t_expenses> _t_expenses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_expenses_category> t_expenses_category
        {
            get
            {
                if ((_t_expenses_category == null))
                {
                    _t_expenses_category = base.CreateObjectSet<t_expenses_category>("t_expenses_category");
                }
                return _t_expenses_category;
            }
        }
        private ObjectSet<t_expenses_category> _t_expenses_category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_incomes> t_incomes
        {
            get
            {
                if ((_t_incomes == null))
                {
                    _t_incomes = base.CreateObjectSet<t_incomes>("t_incomes");
                }
                return _t_incomes;
            }
        }
        private ObjectSet<t_incomes> _t_incomes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_incomes_category> t_incomes_category
        {
            get
            {
                if ((_t_incomes_category == null))
                {
                    _t_incomes_category = base.CreateObjectSet<t_incomes_category>("t_incomes_category");
                }
                return _t_incomes_category;
            }
        }
        private ObjectSet<t_incomes_category> _t_incomes_category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_payment_methods> t_payment_methods
        {
            get
            {
                if ((_t_payment_methods == null))
                {
                    _t_payment_methods = base.CreateObjectSet<t_payment_methods>("t_payment_methods");
                }
                return _t_payment_methods;
            }
        }
        private ObjectSet<t_payment_methods> _t_payment_methods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<viw> viws
        {
            get
            {
                if ((_viws == null))
                {
                    _viws = base.CreateObjectSet<viw>("viws");
                }
                return _viws;
            }
        }
        private ObjectSet<viw> _viws;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<viwin> viwins
        {
            get
            {
                if ((_viwins == null))
                {
                    _viwins = base.CreateObjectSet<viwin>("viwins");
                }
                return _viwins;
            }
        }
        private ObjectSet<viwin> _viwins;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categoryviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategoryviews(categoryview categoryview)
        {
            base.AddObject("categoryviews", categoryview);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_expenses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_expenses(t_expenses t_expenses)
        {
            base.AddObject("t_expenses", t_expenses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_expenses_category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_expenses_category(t_expenses_category t_expenses_category)
        {
            base.AddObject("t_expenses_category", t_expenses_category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_incomes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_incomes(t_incomes t_incomes)
        {
            base.AddObject("t_incomes", t_incomes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_incomes_category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_incomes_category(t_incomes_category t_incomes_category)
        {
            base.AddObject("t_incomes_category", t_incomes_category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_payment_methods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_payment_methods(t_payment_methods t_payment_methods)
        {
            base.AddObject("t_payment_methods", t_payment_methods);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the viws EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToviws(viw viw)
        {
            base.AddObject("viws", viw);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the viwins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToviwins(viwin viwin)
        {
            base.AddObject("viwins", viwin);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="categoryview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categoryview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new categoryview object.
        /// </summary>
        /// <param name="kEY">Initial value of the KEY property.</param>
        /// <param name="vALUE">Initial value of the VALUE property.</param>
        public static categoryview Createcategoryview(global::System.String kEY, global::System.String vALUE)
        {
            categoryview categoryview = new categoryview();
            categoryview.KEY = kEY;
            categoryview.VALUE = vALUE;
            return categoryview;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KEY
        {
            get
            {
                return _KEY;
            }
            set
            {
                if (_KEY != value)
                {
                    OnKEYChanging(value);
                    ReportPropertyChanging("KEY");
                    _KEY = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("KEY");
                    OnKEYChanged();
                }
            }
        }
        private global::System.String _KEY;
        partial void OnKEYChanging(global::System.String value);
        partial void OnKEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VALUE
        {
            get
            {
                return _VALUE;
            }
            set
            {
                if (_VALUE != value)
                {
                    OnVALUEChanging(value);
                    ReportPropertyChanging("VALUE");
                    _VALUE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VALUE");
                    OnVALUEChanged();
                }
            }
        }
        private global::System.String _VALUE;
        partial void OnVALUEChanging(global::System.String value);
        partial void OnVALUEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="t_expenses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_expenses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_expenses object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="aMOUNT">Initial value of the AMOUNT property.</param>
        /// <param name="cATEGORY">Initial value of the CATEGORY property.</param>
        /// <param name="mETHOD">Initial value of the METHOD property.</param>
        public static t_expenses Createt_expenses(global::System.Int64 id, global::System.Double aMOUNT, global::System.Int64 cATEGORY, global::System.Int32 mETHOD)
        {
            t_expenses t_expenses = new t_expenses();
            t_expenses.ID = id;
            t_expenses.AMOUNT = aMOUNT;
            t_expenses.CATEGORY = cATEGORY;
            t_expenses.METHOD = mETHOD;
            return t_expenses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AMOUNT
        {
            get
            {
                return _AMOUNT;
            }
            set
            {
                OnAMOUNTChanging(value);
                ReportPropertyChanging("AMOUNT");
                _AMOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNT");
                OnAMOUNTChanged();
            }
        }
        private global::System.Double _AMOUNT;
        partial void OnAMOUNTChanging(global::System.Double value);
        partial void OnAMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EXP_DATE
        {
            get
            {
                return _EXP_DATE;
            }
            set
            {
                OnEXP_DATEChanging(value);
                ReportPropertyChanging("EXP_DATE");
                _EXP_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXP_DATE");
                OnEXP_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _EXP_DATE;
        partial void OnEXP_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnEXP_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CATEGORY
        {
            get
            {
                return _CATEGORY;
            }
            set
            {
                OnCATEGORYChanging(value);
                ReportPropertyChanging("CATEGORY");
                _CATEGORY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CATEGORY");
                OnCATEGORYChanged();
            }
        }
        private global::System.Int64 _CATEGORY;
        partial void OnCATEGORYChanging(global::System.Int64 value);
        partial void OnCATEGORYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 METHOD
        {
            get
            {
                return _METHOD;
            }
            set
            {
                OnMETHODChanging(value);
                ReportPropertyChanging("METHOD");
                _METHOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("METHOD");
                OnMETHODChanged();
            }
        }
        private global::System.Int32 _METHOD;
        partial void OnMETHODChanging(global::System.Int32 value);
        partial void OnMETHODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                OnCOMMENTSChanging(value);
                ReportPropertyChanging("COMMENTS");
                _COMMENTS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENTS");
                OnCOMMENTSChanged();
            }
        }
        private global::System.String _COMMENTS;
        partial void OnCOMMENTSChanging(global::System.String value);
        partial void OnCOMMENTSChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "EXP_CATEGORY_NAME", "t_expenses_category")]
        public t_expenses_category t_expenses_category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_expenses_category>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses_category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_expenses_category>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses_category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_expenses_category> t_expenses_categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_expenses_category>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses_category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_expenses_category>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses_category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "EXP_PAYMENT_METHOD", "t_payment_methods")]
        public t_payment_methods t_payment_methods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.EXP_PAYMENT_METHOD", "t_payment_methods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.EXP_PAYMENT_METHOD", "t_payment_methods").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_payment_methods> t_payment_methodsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.EXP_PAYMENT_METHOD", "t_payment_methods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_payment_methods>("myhome2013Model.EXP_PAYMENT_METHOD", "t_payment_methods", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="t_expenses_category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_expenses_category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_expenses_category object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static t_expenses_category Createt_expenses_category(global::System.Int64 id, global::System.String nAME)
        {
            t_expenses_category t_expenses_category = new t_expenses_category();
            t_expenses_category.ID = id;
            t_expenses_category.NAME = nAME;
            return t_expenses_category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "EXP_CATEGORY_NAME", "t_expenses")]
        public EntityCollection<t_expenses> t_expenses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_expenses>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_expenses>("myhome2013Model.EXP_CATEGORY_NAME", "t_expenses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="t_incomes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_incomes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_incomes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="aMOUNT">Initial value of the AMOUNT property.</param>
        /// <param name="cATEGORY">Initial value of the CATEGORY property.</param>
        /// <param name="mETHOD">Initial value of the METHOD property.</param>
        public static t_incomes Createt_incomes(global::System.Int64 id, global::System.Double aMOUNT, global::System.Int32 cATEGORY, global::System.Int32 mETHOD)
        {
            t_incomes t_incomes = new t_incomes();
            t_incomes.ID = id;
            t_incomes.AMOUNT = aMOUNT;
            t_incomes.CATEGORY = cATEGORY;
            t_incomes.METHOD = mETHOD;
            return t_incomes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AMOUNT
        {
            get
            {
                return _AMOUNT;
            }
            set
            {
                OnAMOUNTChanging(value);
                ReportPropertyChanging("AMOUNT");
                _AMOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNT");
                OnAMOUNTChanged();
            }
        }
        private global::System.Double _AMOUNT;
        partial void OnAMOUNTChanging(global::System.Double value);
        partial void OnAMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> INC_DATE
        {
            get
            {
                return _INC_DATE;
            }
            set
            {
                OnINC_DATEChanging(value);
                ReportPropertyChanging("INC_DATE");
                _INC_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INC_DATE");
                OnINC_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _INC_DATE;
        partial void OnINC_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnINC_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CATEGORY
        {
            get
            {
                return _CATEGORY;
            }
            set
            {
                OnCATEGORYChanging(value);
                ReportPropertyChanging("CATEGORY");
                _CATEGORY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CATEGORY");
                OnCATEGORYChanged();
            }
        }
        private global::System.Int32 _CATEGORY;
        partial void OnCATEGORYChanging(global::System.Int32 value);
        partial void OnCATEGORYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 METHOD
        {
            get
            {
                return _METHOD;
            }
            set
            {
                OnMETHODChanging(value);
                ReportPropertyChanging("METHOD");
                _METHOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("METHOD");
                OnMETHODChanged();
            }
        }
        private global::System.Int32 _METHOD;
        partial void OnMETHODChanging(global::System.Int32 value);
        partial void OnMETHODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                OnCOMMENTSChanging(value);
                ReportPropertyChanging("COMMENTS");
                _COMMENTS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENTS");
                OnCOMMENTSChanged();
            }
        }
        private global::System.String _COMMENTS;
        partial void OnCOMMENTSChanging(global::System.String value);
        partial void OnCOMMENTSChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "INC_CATEGORY_NAME", "t_incomes_category")]
        public t_incomes_category t_incomes_category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_incomes_category>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes_category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_incomes_category>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes_category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_incomes_category> t_incomes_categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_incomes_category>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes_category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_incomes_category>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes_category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "INC_PAYMENT_METHOD", "t_payment_methods")]
        public t_payment_methods t_payment_methods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.INC_PAYMENT_METHOD", "t_payment_methods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.INC_PAYMENT_METHOD", "t_payment_methods").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_payment_methods> t_payment_methodsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_payment_methods>("myhome2013Model.INC_PAYMENT_METHOD", "t_payment_methods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_payment_methods>("myhome2013Model.INC_PAYMENT_METHOD", "t_payment_methods", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="t_incomes_category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_incomes_category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_incomes_category object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static t_incomes_category Createt_incomes_category(global::System.Int32 id, global::System.String nAME)
        {
            t_incomes_category t_incomes_category = new t_incomes_category();
            t_incomes_category.ID = id;
            t_incomes_category.NAME = nAME;
            return t_incomes_category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "INC_CATEGORY_NAME", "t_incomes")]
        public EntityCollection<t_incomes> t_incomes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_incomes>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_incomes>("myhome2013Model.INC_CATEGORY_NAME", "t_incomes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="t_payment_methods")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_payment_methods : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_payment_methods object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static t_payment_methods Createt_payment_methods(global::System.Int32 id, global::System.String nAME)
        {
            t_payment_methods t_payment_methods = new t_payment_methods();
            t_payment_methods.ID = id;
            t_payment_methods.NAME = nAME;
            return t_payment_methods;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "EXP_PAYMENT_METHOD", "t_expenses")]
        public EntityCollection<t_expenses> t_expenses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_expenses>("myhome2013Model.EXP_PAYMENT_METHOD", "t_expenses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_expenses>("myhome2013Model.EXP_PAYMENT_METHOD", "t_expenses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myhome2013Model", "INC_PAYMENT_METHOD", "t_incomes")]
        public EntityCollection<t_incomes> t_incomes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_incomes>("myhome2013Model.INC_PAYMENT_METHOD", "t_incomes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_incomes>("myhome2013Model.INC_PAYMENT_METHOD", "t_incomes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="viw")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class viw : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new viw object.
        /// </summary>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="payment_Method">Initial value of the Payment_Method property.</param>
        public static viw Createviw(global::System.Double amount, global::System.String category, global::System.String payment_Method)
        {
            viw viw = new viw();
            viw.Amount = amount;
            viw.Category = category;
            viw.Payment_Method = payment_Method;
            return viw;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expense_date
        {
            get
            {
                return _Expense_date;
            }
            set
            {
                OnExpense_dateChanging(value);
                ReportPropertyChanging("Expense_date");
                _Expense_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expense_date");
                OnExpense_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expense_date;
        partial void OnExpense_dateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpense_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if (_Amount != value)
                {
                    OnAmountChanging(value);
                    ReportPropertyChanging("Amount");
                    _Amount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Amount");
                    OnAmountChanged();
                }
            }
        }
        private global::System.Double _Amount;
        partial void OnAmountChanging(global::System.Double value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                if (_Category != value)
                {
                    OnCategoryChanging(value);
                    ReportPropertyChanging("Category");
                    _Category = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Category");
                    OnCategoryChanged();
                }
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Payment_Method
        {
            get
            {
                return _Payment_Method;
            }
            set
            {
                if (_Payment_Method != value)
                {
                    OnPayment_MethodChanging(value);
                    ReportPropertyChanging("Payment_Method");
                    _Payment_Method = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Payment_Method");
                    OnPayment_MethodChanged();
                }
            }
        }
        private global::System.String _Payment_Method;
        partial void OnPayment_MethodChanging(global::System.String value);
        partial void OnPayment_MethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myhome2013Model", Name="viwin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class viwin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new viwin object.
        /// </summary>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="payment_Method">Initial value of the Payment_Method property.</param>
        public static viwin Createviwin(global::System.Double amount, global::System.String category, global::System.String payment_Method)
        {
            viwin viwin = new viwin();
            viwin.Amount = amount;
            viwin.Category = category;
            viwin.Payment_Method = payment_Method;
            return viwin;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Income_Date
        {
            get
            {
                return _Income_Date;
            }
            set
            {
                OnIncome_DateChanging(value);
                ReportPropertyChanging("Income_Date");
                _Income_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Income_Date");
                OnIncome_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Income_Date;
        partial void OnIncome_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnIncome_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if (_Amount != value)
                {
                    OnAmountChanging(value);
                    ReportPropertyChanging("Amount");
                    _Amount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Amount");
                    OnAmountChanged();
                }
            }
        }
        private global::System.Double _Amount;
        partial void OnAmountChanging(global::System.Double value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                if (_Category != value)
                {
                    OnCategoryChanging(value);
                    ReportPropertyChanging("Category");
                    _Category = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Category");
                    OnCategoryChanged();
                }
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Payment_Method
        {
            get
            {
                return _Payment_Method;
            }
            set
            {
                if (_Payment_Method != value)
                {
                    OnPayment_MethodChanging(value);
                    ReportPropertyChanging("Payment_Method");
                    _Payment_Method = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Payment_Method");
                    OnPayment_MethodChanged();
                }
            }
        }
        private global::System.String _Payment_Method;
        partial void OnPayment_MethodChanging(global::System.String value);
        partial void OnPayment_MethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion
    
    }

    #endregion
    
}
